/** 
 * Autogenerated by Recite18th from table piteng.akses
 * Don't change this file. Instead, change the derived class AksesModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _AksesModel extends Model
{
    public String Nip;
    public String Name;
    public String Password;
    public String Email;
    public String Hak_Akses;
    public _AksesModel()
    {
        tableName="akses";
        pkFieldName="Nip";
        fqn = AksesModel.class.getName();
        plainClassName = "AksesModel";
    }
    public void setNip(String Nip)
    {
        this.Nip=Nip;
    }
    public String getNip()
    {        return this.Nip;
    }
    public void setName(String Name)
    {
        this.Name=Name;
    }
    public String getName()
    {        return this.Name;
    }
    public void setPassword(String Password)
    {
        this.Password=Password;
    }
    public String getPassword()
    {        return this.Password;
    }
    public void setEmail(String Email)
    {
        this.Email=Email;
    }
    public String getEmail()
    {        return this.Email;
    }
    public void setHak_Akses(String Hak_Akses)
    {
        this.Hak_Akses=Hak_Akses;
    }
    public String getHak_Akses()
    {        return this.Hak_Akses;
    }
    public void get()
    {
        _AksesModel result = (_AksesModel) super.getModel();
        if(result!=null)
        {
            setNip(result.getNip());
            setName(result.getName());
            setPassword(result.getPassword());
            setEmail(result.getEmail());
            setHak_Akses(result.getHak_Akses());
        }
    }
}
