/** 
 * Autogenerated by Recite18th from table piteng.cuti
 * Don't change this file. Instead, change the derived class CutiModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _CutiModel extends Model
{
    public String idcuti;
    public String nip;
    public String jenis_cuti;
    public String no_surat_ijin_cuti;
    public String tgl_surat_ijin_cuti;
    public String tgl_awal_cuti;
    public String tgl_akhir_cuti;
    public String pejabat_berwenang;
    public _CutiModel()
    {
        tableName="cuti";
        pkFieldName="idcuti";
        fqn = CutiModel.class.getName();
        plainClassName = "CutiModel";
    }
    public void setIdcuti(String idcuti)
    {
        this.idcuti=idcuti;
    }
    public String getIdcuti()
    {        return this.idcuti;
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setJenis_cuti(String jenis_cuti)
    {
        this.jenis_cuti=jenis_cuti;
    }
    public String getJenis_cuti()
    {        return this.jenis_cuti;
    }
    public void setNo_surat_ijin_cuti(String no_surat_ijin_cuti)
    {
        this.no_surat_ijin_cuti=no_surat_ijin_cuti;
    }
    public String getNo_surat_ijin_cuti()
    {        return this.no_surat_ijin_cuti;
    }
    public void setTgl_surat_ijin_cuti(String tgl_surat_ijin_cuti)
    {
        this.tgl_surat_ijin_cuti=tgl_surat_ijin_cuti;
    }
    public String getTgl_surat_ijin_cuti()
    {        return this.tgl_surat_ijin_cuti;
    }
    public void setTgl_awal_cuti(String tgl_awal_cuti)
    {
        this.tgl_awal_cuti=tgl_awal_cuti;
    }
    public String getTgl_awal_cuti()
    {        return this.tgl_awal_cuti;
    }
    public void setTgl_akhir_cuti(String tgl_akhir_cuti)
    {
        this.tgl_akhir_cuti=tgl_akhir_cuti;
    }
    public String getTgl_akhir_cuti()
    {        return this.tgl_akhir_cuti;
    }
    public void setPejabat_berwenang(String pejabat_berwenang)
    {
        this.pejabat_berwenang=pejabat_berwenang;
    }
    public String getPejabat_berwenang()
    {        return this.pejabat_berwenang;
    }
    public void get()
    {
        _CutiModel result = (_CutiModel) super.getModel();
        if(result!=null)
        {
            setIdcuti(result.getIdcuti());
            setNip(result.getNip());
            setJenis_cuti(result.getJenis_cuti());
            setNo_surat_ijin_cuti(result.getNo_surat_ijin_cuti());
            setTgl_surat_ijin_cuti(result.getTgl_surat_ijin_cuti());
            setTgl_awal_cuti(result.getTgl_awal_cuti());
            setTgl_akhir_cuti(result.getTgl_akhir_cuti());
            setPejabat_berwenang(result.getPejabat_berwenang());
        }
    }
}
