/** 
 * Autogenerated by Recite18th from table piteng.diklat
 * Don't change this file. Instead, change the derived class DiklatModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _DiklatModel extends Model
{
    public String iddiklat;
    public String nip;
    public String nama_diklat;
    public String tempat;
    public String penyelenggara;
    public String tgl_mulai;
    public String tgl_selesai;
    public String no_sttpl;
    public String tgl_sttpl;
    public String jumlah_jam;
    public _DiklatModel()
    {
        tableName="diklat";
        pkFieldName="iddiklat";
        fqn = DiklatModel.class.getName();
        plainClassName = "DiklatModel";
    }
    public void setIddiklat(String iddiklat)
    {
        this.iddiklat=iddiklat;
    }
    public String getIddiklat()
    {        return this.iddiklat;
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setNama_diklat(String nama_diklat)
    {
        this.nama_diklat=nama_diklat;
    }
    public String getNama_diklat()
    {        return this.nama_diklat;
    }
    public void setTempat(String tempat)
    {
        this.tempat=tempat;
    }
    public String getTempat()
    {        return this.tempat;
    }
    public void setPenyelenggara(String penyelenggara)
    {
        this.penyelenggara=penyelenggara;
    }
    public String getPenyelenggara()
    {        return this.penyelenggara;
    }
    public void setTgl_mulai(String tgl_mulai)
    {
        this.tgl_mulai=tgl_mulai;
    }
    public String getTgl_mulai()
    {        return this.tgl_mulai;
    }
    public void setTgl_selesai(String tgl_selesai)
    {
        this.tgl_selesai=tgl_selesai;
    }
    public String getTgl_selesai()
    {        return this.tgl_selesai;
    }
    public void setNo_sttpl(String no_sttpl)
    {
        this.no_sttpl=no_sttpl;
    }
    public String getNo_sttpl()
    {        return this.no_sttpl;
    }
    public void setTgl_sttpl(String tgl_sttpl)
    {
        this.tgl_sttpl=tgl_sttpl;
    }
    public String getTgl_sttpl()
    {        return this.tgl_sttpl;
    }
    public void setJumlah_jam(String jumlah_jam)
    {
        this.jumlah_jam=jumlah_jam;
    }
    public String getJumlah_jam()
    {        return this.jumlah_jam;
    }
    public void get()
    {
        _DiklatModel result = (_DiklatModel) super.getModel();
        if(result!=null)
        {
            setIddiklat(result.getIddiklat());
            setNip(result.getNip());
            setNama_diklat(result.getNama_diklat());
            setTempat(result.getTempat());
            setPenyelenggara(result.getPenyelenggara());
            setTgl_mulai(result.getTgl_mulai());
            setTgl_selesai(result.getTgl_selesai());
            setNo_sttpl(result.getNo_sttpl());
            setTgl_sttpl(result.getTgl_sttpl());
            setJumlah_jam(result.getJumlah_jam());
        }
    }
}
