/** 
 * Autogenerated by Recite18th from table piteng.jabatan
 * Don't change this file. Instead, change the derived class JabatanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _JabatanModel extends Model
{
    public String idjabatan;
    public String nip;
    public String nama_jabatan;
    public String jenis_Jabatan;
    public String eselon;
    public String unit_kerja;
    public String kode_sub_unit_kerja;
    public String tmt_jabatan;
    public String no_sk_jabatan;
    public String tgl_sk_jabatan;
    public String no_surat_pelantikan;
    public String tgl_surat_pelantikan;
    public String pejabat_berwenang;
    public String kode_bagian_unit_kerja;
    public _JabatanModel()
    {
        tableName="jabatan";
        pkFieldName="idjabatan";
        fqn = JabatanModel.class.getName();
        plainClassName = "JabatanModel";
    }
    public void setIdjabatan(String idjabatan)
    {
        this.idjabatan=idjabatan;
    }
    public String getIdjabatan()
    {        return this.idjabatan;
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setNama_jabatan(String nama_jabatan)
    {
        this.nama_jabatan=nama_jabatan;
    }
    public String getNama_jabatan()
    {        return this.nama_jabatan;
    }
    public void setJenis_Jabatan(String jenis_Jabatan)
    {
        this.jenis_Jabatan=jenis_Jabatan;
    }
    public String getJenis_Jabatan()
    {        return this.jenis_Jabatan;
    }
    public void setEselon(String eselon)
    {
        this.eselon=eselon;
    }
    public String getEselon()
    {        return this.eselon;
    }
    public void setUnit_kerja(String unit_kerja)
    {
        this.unit_kerja=unit_kerja;
    }
    public String getUnit_kerja()
    {        return this.unit_kerja;
    }
    public void setKode_sub_unit_kerja(String kode_sub_unit_kerja)
    {
        this.kode_sub_unit_kerja=kode_sub_unit_kerja;
    }
    public String getKode_sub_unit_kerja()
    {        return this.kode_sub_unit_kerja;
    }
    public void setTmt_jabatan(String tmt_jabatan)
    {
        this.tmt_jabatan=tmt_jabatan;
    }
    public String getTmt_jabatan()
    {        return this.tmt_jabatan;
    }
    public void setNo_sk_jabatan(String no_sk_jabatan)
    {
        this.no_sk_jabatan=no_sk_jabatan;
    }
    public String getNo_sk_jabatan()
    {        return this.no_sk_jabatan;
    }
    public void setTgl_sk_jabatan(String tgl_sk_jabatan)
    {
        this.tgl_sk_jabatan=tgl_sk_jabatan;
    }
    public String getTgl_sk_jabatan()
    {        return this.tgl_sk_jabatan;
    }
    public void setNo_surat_pelantikan(String no_surat_pelantikan)
    {
        this.no_surat_pelantikan=no_surat_pelantikan;
    }
    public String getNo_surat_pelantikan()
    {        return this.no_surat_pelantikan;
    }
    public void setTgl_surat_pelantikan(String tgl_surat_pelantikan)
    {
        this.tgl_surat_pelantikan=tgl_surat_pelantikan;
    }
    public String getTgl_surat_pelantikan()
    {        return this.tgl_surat_pelantikan;
    }
    public void setPejabat_berwenang(String pejabat_berwenang)
    {
        this.pejabat_berwenang=pejabat_berwenang;
    }
    public String getPejabat_berwenang()
    {        return this.pejabat_berwenang;
    }
    public void setKode_bagian_unit_kerja(String kode_bagian_unit_kerja)
    {
        this.kode_bagian_unit_kerja=kode_bagian_unit_kerja;
    }
    public String getKode_bagian_unit_kerja()
    {        return this.kode_bagian_unit_kerja;
    }
    public void get()
    {
        _JabatanModel result = (_JabatanModel) super.getModel();
        if(result!=null)
        {
            setIdjabatan(result.getIdjabatan());
            setNip(result.getNip());
            setNama_jabatan(result.getNama_jabatan());
            setJenis_Jabatan(result.getJenis_Jabatan());
            setEselon(result.getEselon());
            setUnit_kerja(result.getUnit_kerja());
            setKode_sub_unit_kerja(result.getKode_sub_unit_kerja());
            setTmt_jabatan(result.getTmt_jabatan());
            setNo_sk_jabatan(result.getNo_sk_jabatan());
            setTgl_sk_jabatan(result.getTgl_sk_jabatan());
            setNo_surat_pelantikan(result.getNo_surat_pelantikan());
            setTgl_surat_pelantikan(result.getTgl_surat_pelantikan());
            setPejabat_berwenang(result.getPejabat_berwenang());
            setKode_bagian_unit_kerja(result.getKode_bagian_unit_kerja());
        }
    }
}
