/** 
 * Autogenerated by Recite18th from table piteng.kursus_penataran
 * Don't change this file. Instead, change the derived class KursusPenataranModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _KursusPenataranModel extends Model
{
    public String idkursus_penataran;
    public String nip;
    public String nama_kursus_penataran;
    public String tempat;
    public String penyelenggara;
    public String tgl_mulai;
    public String tgl_selesai;
    public String no_sertifikat;
    public String tgl_sertifikat;
    public String jumlah_jam;
    public String jenis;
    public _KursusPenataranModel()
    {
        tableName="kursus_penataran";
        pkFieldName="idkursus_penataran";
        fqn = KursusPenataranModel.class.getName();
        plainClassName = "KursusPenataranModel";
    }
    public void setIdkursus_penataran(String idkursus_penataran)
    {
        this.idkursus_penataran=idkursus_penataran;
    }
    public String getIdkursus_penataran()
    {        return this.idkursus_penataran;
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setNama_kursus_penataran(String nama_kursus_penataran)
    {
        this.nama_kursus_penataran=nama_kursus_penataran;
    }
    public String getNama_kursus_penataran()
    {        return this.nama_kursus_penataran;
    }
    public void setTempat(String tempat)
    {
        this.tempat=tempat;
    }
    public String getTempat()
    {        return this.tempat;
    }
    public void setPenyelenggara(String penyelenggara)
    {
        this.penyelenggara=penyelenggara;
    }
    public String getPenyelenggara()
    {        return this.penyelenggara;
    }
    public void setTgl_mulai(String tgl_mulai)
    {
        this.tgl_mulai=tgl_mulai;
    }
    public String getTgl_mulai()
    {        return this.tgl_mulai;
    }
    public void setTgl_selesai(String tgl_selesai)
    {
        this.tgl_selesai=tgl_selesai;
    }
    public String getTgl_selesai()
    {        return this.tgl_selesai;
    }
    public void setNo_sertifikat(String no_sertifikat)
    {
        this.no_sertifikat=no_sertifikat;
    }
    public String getNo_sertifikat()
    {        return this.no_sertifikat;
    }
    public void setTgl_sertifikat(String tgl_sertifikat)
    {
        this.tgl_sertifikat=tgl_sertifikat;
    }
    public String getTgl_sertifikat()
    {        return this.tgl_sertifikat;
    }
    public void setJumlah_jam(String jumlah_jam)
    {
        this.jumlah_jam=jumlah_jam;
    }
    public String getJumlah_jam()
    {        return this.jumlah_jam;
    }
    public void setJenis(String jenis)
    {
        this.jenis=jenis;
    }
    public String getJenis()
    {        return this.jenis;
    }
    public void get()
    {
        _KursusPenataranModel result = (_KursusPenataranModel) super.getModel();
        if(result!=null)
        {
            setIdkursus_penataran(result.getIdkursus_penataran());
            setNip(result.getNip());
            setNama_kursus_penataran(result.getNama_kursus_penataran());
            setTempat(result.getTempat());
            setPenyelenggara(result.getPenyelenggara());
            setTgl_mulai(result.getTgl_mulai());
            setTgl_selesai(result.getTgl_selesai());
            setNo_sertifikat(result.getNo_sertifikat());
            setTgl_sertifikat(result.getTgl_sertifikat());
            setJumlah_jam(result.getJumlah_jam());
            setJenis(result.getJenis());
        }
    }
}
