/** 
 * Autogenerated by Recite18th from table piteng.naik_pangkat
 * Don't change this file. Instead, change the derived class NaikPangkatModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _NaikPangkatModel extends Model
{
    public String idpangkat;
    public String nip;
    public String jenis_kenaikan_pangkat;
    public String kenaikan_pangkat_pilihan;
    public String tmt_Pangkat;
    public String gaji_pokok;
    public String no_sk_pangkat;
    public String tgl_sk_pangkat;
    public String pejabat_berwenang;
    public String nama_pangkat;
    public _NaikPangkatModel()
    {
        tableName="naik_pangkat";
        pkFieldName="idpangkat";
        fqn = NaikPangkatModel.class.getName();
        plainClassName = "NaikPangkatModel";
    }
    public void setIdpangkat(String idpangkat)
    {
        this.idpangkat=idpangkat;
    }
    public String getIdpangkat()
    {        return this.idpangkat;
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setJenis_kenaikan_pangkat(String jenis_kenaikan_pangkat)
    {
        this.jenis_kenaikan_pangkat=jenis_kenaikan_pangkat;
    }
    public String getJenis_kenaikan_pangkat()
    {        return this.jenis_kenaikan_pangkat;
    }
    public void setKenaikan_pangkat_pilihan(String kenaikan_pangkat_pilihan)
    {
        this.kenaikan_pangkat_pilihan=kenaikan_pangkat_pilihan;
    }
    public String getKenaikan_pangkat_pilihan()
    {        return this.kenaikan_pangkat_pilihan;
    }
    public void setTmt_Pangkat(String tmt_Pangkat)
    {
        this.tmt_Pangkat=tmt_Pangkat;
    }
    public String getTmt_Pangkat()
    {        return this.tmt_Pangkat;
    }
    public void setGaji_pokok(String gaji_pokok)
    {
        this.gaji_pokok=gaji_pokok;
    }
    public String getGaji_pokok()
    {        return this.gaji_pokok;
    }
    public void setNo_sk_pangkat(String no_sk_pangkat)
    {
        this.no_sk_pangkat=no_sk_pangkat;
    }
    public String getNo_sk_pangkat()
    {        return this.no_sk_pangkat;
    }
    public void setTgl_sk_pangkat(String tgl_sk_pangkat)
    {
        this.tgl_sk_pangkat=tgl_sk_pangkat;
    }
    public String getTgl_sk_pangkat()
    {        return this.tgl_sk_pangkat;
    }
    public void setPejabat_berwenang(String pejabat_berwenang)
    {
        this.pejabat_berwenang=pejabat_berwenang;
    }
    public String getPejabat_berwenang()
    {        return this.pejabat_berwenang;
    }
    public void setNama_pangkat(String nama_pangkat)
    {
        this.nama_pangkat=nama_pangkat;
    }
    public String getNama_pangkat()
    {        return this.nama_pangkat;
    }
    public void get()
    {
        _NaikPangkatModel result = (_NaikPangkatModel) super.getModel();
        if(result!=null)
        {
            setIdpangkat(result.getIdpangkat());
            setNip(result.getNip());
            setJenis_kenaikan_pangkat(result.getJenis_kenaikan_pangkat());
            setKenaikan_pangkat_pilihan(result.getKenaikan_pangkat_pilihan());
            setTmt_Pangkat(result.getTmt_Pangkat());
            setGaji_pokok(result.getGaji_pokok());
            setNo_sk_pangkat(result.getNo_sk_pangkat());
            setTgl_sk_pangkat(result.getTgl_sk_pangkat());
            setPejabat_berwenang(result.getPejabat_berwenang());
            setNama_pangkat(result.getNama_pangkat());
        }
    }
}
