/** 
 * Autogenerated by Recite18th from table piteng.pegawai
 * Don't change this file. Instead, change the derived class PegawaiModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PegawaiModel extends Model
{
    public String nip;
    public String no_karpeg;
    public String no_kartu_askes;
    public String nama_pegawai;
    public String tempat_lahir;
    public String tgl_lahir;
    public String jenis_kelamin;
    public String agama;
    public String golongan_darah;
    public String status_perkawinan;
    public String pendidikan_terakhir;
    public String status_kepegawaian;
    public String pangkat_golongan_ruang;
    public String tmt_pangkat;
    public String no_sk;
    public String tgl_mulai_kerja;
    public String pejabat_berwenang;
    public String unit_kerja;
    public String kode_bagian_unit_kerja;
    public String kode_sub_unit_kerja;
    public String no_ktp;
    public String alamat_ktp;
    public String alamat_domisili;
    public String foto;
    public _PegawaiModel()
    {
        tableName="pegawai";
        pkFieldName="nip";
        fqn = PegawaiModel.class.getName();
        plainClassName = "PegawaiModel";
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setNo_karpeg(String no_karpeg)
    {
        this.no_karpeg=no_karpeg;
    }
    public String getNo_karpeg()
    {        return this.no_karpeg;
    }
    public void setNo_kartu_askes(String no_kartu_askes)
    {
        this.no_kartu_askes=no_kartu_askes;
    }
    public String getNo_kartu_askes()
    {        return this.no_kartu_askes;
    }
    public void setNama_pegawai(String nama_pegawai)
    {
        this.nama_pegawai=nama_pegawai;
    }
    public String getNama_pegawai()
    {        return this.nama_pegawai;
    }
    public void setTempat_lahir(String tempat_lahir)
    {
        this.tempat_lahir=tempat_lahir;
    }
    public String getTempat_lahir()
    {        return this.tempat_lahir;
    }
    public void setTgl_lahir(String tgl_lahir)
    {
        this.tgl_lahir=tgl_lahir;
    }
    public String getTgl_lahir()
    {        return this.tgl_lahir;
    }
    public void setJenis_kelamin(String jenis_kelamin)
    {
        this.jenis_kelamin=jenis_kelamin;
    }
    public String getJenis_kelamin()
    {        return this.jenis_kelamin;
    }
    public void setAgama(String agama)
    {
        this.agama=agama;
    }
    public String getAgama()
    {        return this.agama;
    }
    public void setGolongan_darah(String golongan_darah)
    {
        this.golongan_darah=golongan_darah;
    }
    public String getGolongan_darah()
    {        return this.golongan_darah;
    }
    public void setStatus_perkawinan(String status_perkawinan)
    {
        this.status_perkawinan=status_perkawinan;
    }
    public String getStatus_perkawinan()
    {        return this.status_perkawinan;
    }
    public void setPendidikan_terakhir(String pendidikan_terakhir)
    {
        this.pendidikan_terakhir=pendidikan_terakhir;
    }
    public String getPendidikan_terakhir()
    {        return this.pendidikan_terakhir;
    }
    public void setStatus_kepegawaian(String status_kepegawaian)
    {
        this.status_kepegawaian=status_kepegawaian;
    }
    public String getStatus_kepegawaian()
    {        return this.status_kepegawaian;
    }
    public void setPangkat_golongan_ruang(String pangkat_golongan_ruang)
    {
        this.pangkat_golongan_ruang=pangkat_golongan_ruang;
    }
    public String getPangkat_golongan_ruang()
    {        return this.pangkat_golongan_ruang;
    }
    public void setTmt_pangkat(String tmt_pangkat)
    {
        this.tmt_pangkat=tmt_pangkat;
    }
    public String getTmt_pangkat()
    {        return this.tmt_pangkat;
    }
    public void setNo_sk(String no_sk)
    {
        this.no_sk=no_sk;
    }
    public String getNo_sk()
    {        return this.no_sk;
    }
    public void setTgl_mulai_kerja(String tgl_mulai_kerja)
    {
        this.tgl_mulai_kerja=tgl_mulai_kerja;
    }
    public String getTgl_mulai_kerja()
    {        return this.tgl_mulai_kerja;
    }
    public void setPejabat_berwenang(String pejabat_berwenang)
    {
        this.pejabat_berwenang=pejabat_berwenang;
    }
    public String getPejabat_berwenang()
    {        return this.pejabat_berwenang;
    }
    public void setUnit_kerja(String unit_kerja)
    {
        this.unit_kerja=unit_kerja;
    }
    public String getUnit_kerja()
    {        return this.unit_kerja;
    }
    public void setKode_bagian_unit_kerja(String kode_bagian_unit_kerja)
    {
        this.kode_bagian_unit_kerja=kode_bagian_unit_kerja;
    }
    public String getKode_bagian_unit_kerja()
    {        return this.kode_bagian_unit_kerja;
    }
    public void setKode_sub_unit_kerja(String kode_sub_unit_kerja)
    {
        this.kode_sub_unit_kerja=kode_sub_unit_kerja;
    }
    public String getKode_sub_unit_kerja()
    {        return this.kode_sub_unit_kerja;
    }
    public void setNo_ktp(String no_ktp)
    {
        this.no_ktp=no_ktp;
    }
    public String getNo_ktp()
    {        return this.no_ktp;
    }
    public void setAlamat_ktp(String alamat_ktp)
    {
        this.alamat_ktp=alamat_ktp;
    }
    public String getAlamat_ktp()
    {        return this.alamat_ktp;
    }
    public void setAlamat_domisili(String alamat_domisili)
    {
        this.alamat_domisili=alamat_domisili;
    }
    public String getAlamat_domisili()
    {        return this.alamat_domisili;
    }
    public void setFoto(String foto)
    {
        this.foto=foto;
    }
    public String getFoto()
    {        return this.foto;
    }
    public void get()
    {
        _PegawaiModel result = (_PegawaiModel) super.getModel();
        if(result!=null)
        {
            setNip(result.getNip());
            setNo_karpeg(result.getNo_karpeg());
            setNo_kartu_askes(result.getNo_kartu_askes());
            setNama_pegawai(result.getNama_pegawai());
            setTempat_lahir(result.getTempat_lahir());
            setTgl_lahir(result.getTgl_lahir());
            setJenis_kelamin(result.getJenis_kelamin());
            setAgama(result.getAgama());
            setGolongan_darah(result.getGolongan_darah());
            setStatus_perkawinan(result.getStatus_perkawinan());
            setPendidikan_terakhir(result.getPendidikan_terakhir());
            setStatus_kepegawaian(result.getStatus_kepegawaian());
            setPangkat_golongan_ruang(result.getPangkat_golongan_ruang());
            setTmt_pangkat(result.getTmt_pangkat());
            setNo_sk(result.getNo_sk());
            setTgl_mulai_kerja(result.getTgl_mulai_kerja());
            setPejabat_berwenang(result.getPejabat_berwenang());
            setUnit_kerja(result.getUnit_kerja());
            setKode_bagian_unit_kerja(result.getKode_bagian_unit_kerja());
            setKode_sub_unit_kerja(result.getKode_sub_unit_kerja());
            setNo_ktp(result.getNo_ktp());
            setAlamat_ktp(result.getAlamat_ktp());
            setAlamat_domisili(result.getAlamat_domisili());
            setFoto(result.getFoto());
        }
    }
}
