/** 
 * Autogenerated by Recite18th from table piteng.pendidikan
 * Don't change this file. Instead, change the derived class PendidikanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PendidikanModel extends Model
{
    public String idpendidikan;
    public String nip;
    public String jenjang_pendidikan;
    public String nama_pendidikan;
    public String fakultas;
    public String jurusan;
    public String no_ijazah_sttb;
    public String tgl_ijazah_sttb;
    public _PendidikanModel()
    {
        tableName="pendidikan";
        pkFieldName="idpendidikan";
        fqn = PendidikanModel.class.getName();
        plainClassName = "PendidikanModel";
    }
    public void setIdpendidikan(String idpendidikan)
    {
        this.idpendidikan=idpendidikan;
    }
    public String getIdpendidikan()
    {        return this.idpendidikan;
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setJenjang_pendidikan(String jenjang_pendidikan)
    {
        this.jenjang_pendidikan=jenjang_pendidikan;
    }
    public String getJenjang_pendidikan()
    {        return this.jenjang_pendidikan;
    }
    public void setNama_pendidikan(String nama_pendidikan)
    {
        this.nama_pendidikan=nama_pendidikan;
    }
    public String getNama_pendidikan()
    {        return this.nama_pendidikan;
    }
    public void setFakultas(String fakultas)
    {
        this.fakultas=fakultas;
    }
    public String getFakultas()
    {        return this.fakultas;
    }
    public void setJurusan(String jurusan)
    {
        this.jurusan=jurusan;
    }
    public String getJurusan()
    {        return this.jurusan;
    }
    public void setNo_ijazah_sttb(String no_ijazah_sttb)
    {
        this.no_ijazah_sttb=no_ijazah_sttb;
    }
    public String getNo_ijazah_sttb()
    {        return this.no_ijazah_sttb;
    }
    public void setTgl_ijazah_sttb(String tgl_ijazah_sttb)
    {
        this.tgl_ijazah_sttb=tgl_ijazah_sttb;
    }
    public String getTgl_ijazah_sttb()
    {        return this.tgl_ijazah_sttb;
    }
    public void get()
    {
        _PendidikanModel result = (_PendidikanModel) super.getModel();
        if(result!=null)
        {
            setIdpendidikan(result.getIdpendidikan());
            setNip(result.getNip());
            setJenjang_pendidikan(result.getJenjang_pendidikan());
            setNama_pendidikan(result.getNama_pendidikan());
            setFakultas(result.getFakultas());
            setJurusan(result.getJurusan());
            setNo_ijazah_sttb(result.getNo_ijazah_sttb());
            setTgl_ijazah_sttb(result.getTgl_ijazah_sttb());
        }
    }
}
