/** 
 * Autogenerated by Recite18th from table piteng.prajabatan
 * Don't change this file. Instead, change the derived class PrajabatanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PrajabatanModel extends Model
{
    public String idprajabatan;
    public String nip;
    public String jenis_prajabatan;
    public String tempat;
    public String penyelenggara;
    public String tgl_pelaksanaan;
    public String no_sttpl;
    public String tgl_sttpl;
    public _PrajabatanModel()
    {
        tableName="prajabatan";
        pkFieldName="idprajabatan";
        fqn = PrajabatanModel.class.getName();
        plainClassName = "PrajabatanModel";
    }
    public void setIdprajabatan(String idprajabatan)
    {
        this.idprajabatan=idprajabatan;
    }
    public String getIdprajabatan()
    {        return this.idprajabatan;
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setJenis_prajabatan(String jenis_prajabatan)
    {
        this.jenis_prajabatan=jenis_prajabatan;
    }
    public String getJenis_prajabatan()
    {        return this.jenis_prajabatan;
    }
    public void setTempat(String tempat)
    {
        this.tempat=tempat;
    }
    public String getTempat()
    {        return this.tempat;
    }
    public void setPenyelenggara(String penyelenggara)
    {
        this.penyelenggara=penyelenggara;
    }
    public String getPenyelenggara()
    {        return this.penyelenggara;
    }
    public void setTgl_pelaksanaan(String tgl_pelaksanaan)
    {
        this.tgl_pelaksanaan=tgl_pelaksanaan;
    }
    public String getTgl_pelaksanaan()
    {        return this.tgl_pelaksanaan;
    }
    public void setNo_sttpl(String no_sttpl)
    {
        this.no_sttpl=no_sttpl;
    }
    public String getNo_sttpl()
    {        return this.no_sttpl;
    }
    public void setTgl_sttpl(String tgl_sttpl)
    {
        this.tgl_sttpl=tgl_sttpl;
    }
    public String getTgl_sttpl()
    {        return this.tgl_sttpl;
    }
    public void get()
    {
        _PrajabatanModel result = (_PrajabatanModel) super.getModel();
        if(result!=null)
        {
            setIdprajabatan(result.getIdprajabatan());
            setNip(result.getNip());
            setJenis_prajabatan(result.getJenis_prajabatan());
            setTempat(result.getTempat());
            setPenyelenggara(result.getPenyelenggara());
            setTgl_pelaksanaan(result.getTgl_pelaksanaan());
            setNo_sttpl(result.getNo_sttpl());
            setTgl_sttpl(result.getTgl_sttpl());
        }
    }
}
