/** 
 * Autogenerated by Recite18th from table piteng.suami_istri
 * Don't change this file. Instead, change the derived class SuamiIstriModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _SuamiIstriModel extends Model
{
    public String idsuami_istri;
    public String nip;
    public String nama_suami_istri;
    public String tempat_lahir;
    public String tgl_lahir;
    public String status_suami_istri;
    public String pekerjaan;
    public String status_tunjangan;
    public String tgl_menikah;
    public _SuamiIstriModel()
    {
        tableName="suami_istri";
        pkFieldName="idsuami_istri";
        fqn = SuamiIstriModel.class.getName();
        plainClassName = "SuamiIstriModel";
    }
    public void setIdsuami_istri(String idsuami_istri)
    {
        this.idsuami_istri=idsuami_istri;
    }
    public String getIdsuami_istri()
    {        return this.idsuami_istri;
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setNama_suami_istri(String nama_suami_istri)
    {
        this.nama_suami_istri=nama_suami_istri;
    }
    public String getNama_suami_istri()
    {        return this.nama_suami_istri;
    }
    public void setTempat_lahir(String tempat_lahir)
    {
        this.tempat_lahir=tempat_lahir;
    }
    public String getTempat_lahir()
    {        return this.tempat_lahir;
    }
    public void setTgl_lahir(String tgl_lahir)
    {
        this.tgl_lahir=tgl_lahir;
    }
    public String getTgl_lahir()
    {        return this.tgl_lahir;
    }
    public void setStatus_suami_istri(String status_suami_istri)
    {
        this.status_suami_istri=status_suami_istri;
    }
    public String getStatus_suami_istri()
    {        return this.status_suami_istri;
    }
    public void setPekerjaan(String pekerjaan)
    {
        this.pekerjaan=pekerjaan;
    }
    public String getPekerjaan()
    {        return this.pekerjaan;
    }
    public void setStatus_tunjangan(String status_tunjangan)
    {
        this.status_tunjangan=status_tunjangan;
    }
    public String getStatus_tunjangan()
    {        return this.status_tunjangan;
    }
    public void setTgl_menikah(String tgl_menikah)
    {
        this.tgl_menikah=tgl_menikah;
    }
    public String getTgl_menikah()
    {        return this.tgl_menikah;
    }
    public void get()
    {
        _SuamiIstriModel result = (_SuamiIstriModel) super.getModel();
        if(result!=null)
        {
            setIdsuami_istri(result.getIdsuami_istri());
            setNip(result.getNip());
            setNama_suami_istri(result.getNama_suami_istri());
            setTempat_lahir(result.getTempat_lahir());
            setTgl_lahir(result.getTgl_lahir());
            setStatus_suami_istri(result.getStatus_suami_istri());
            setPekerjaan(result.getPekerjaan());
            setStatus_tunjangan(result.getStatus_tunjangan());
            setTgl_menikah(result.getTgl_menikah());
        }
    }
}
