/** 
 * Autogenerated by Recite18th from table piteng.sub_unit_kerja
 * Don't change this file. Instead, change the derived class SubUnitKerjaModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _SubUnitKerjaModel extends Model
{
    public String kode_sub_unit_kerja;
    public String sub_unit_kerja;
    public String kode_bagian_unit_kerja;
    public _SubUnitKerjaModel()
    {
        tableName="sub_unit_kerja";
        pkFieldName="kode_sub_unit_kerja";
        fqn = SubUnitKerjaModel.class.getName();
        plainClassName = "SubUnitKerjaModel";
    }
    public void setKode_sub_unit_kerja(String kode_sub_unit_kerja)
    {
        this.kode_sub_unit_kerja=kode_sub_unit_kerja;
    }
    public String getKode_sub_unit_kerja()
    {        return this.kode_sub_unit_kerja;
    }
    public void setSub_unit_kerja(String sub_unit_kerja)
    {
        this.sub_unit_kerja=sub_unit_kerja;
    }
    public String getSub_unit_kerja()
    {        return this.sub_unit_kerja;
    }
    public void setKode_bagian_unit_kerja(String kode_bagian_unit_kerja)
    {
        this.kode_bagian_unit_kerja=kode_bagian_unit_kerja;
    }
    public String getKode_bagian_unit_kerja()
    {        return this.kode_bagian_unit_kerja;
    }
    public void get()
    {
        _SubUnitKerjaModel result = (_SubUnitKerjaModel) super.getModel();
        if(result!=null)
        {
            setKode_sub_unit_kerja(result.getKode_sub_unit_kerja());
            setSub_unit_kerja(result.getSub_unit_kerja());
            setKode_bagian_unit_kerja(result.getKode_bagian_unit_kerja());
        }
    }
}
