/** 
 * Autogenerated by Recite18th from table piteng.user_account
 * Don't change this file. Instead, change the derived class UserAccountModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _UserAccountModel extends Model
{
    public String nip;
    public String name;
    public String password;
    public String email;
    public String role;
    public String username;
    public _UserAccountModel()
    {
        tableName="user_account";
        pkFieldName="nip";
        fqn = UserAccountModel.class.getName();
        plainClassName = "UserAccountModel";
    }
    public void setNip(String nip)
    {
        this.nip=nip;
    }
    public String getNip()
    {        return this.nip;
    }
    public void setName(String name)
    {
        this.name=name;
    }
    public String getName()
    {        return this.name;
    }
    public void setPassword(String password)
    {
        this.password=password;
    }
    public String getPassword()
    {        return this.password;
    }
    public void setEmail(String email)
    {
        this.email=email;
    }
    public String getEmail()
    {        return this.email;
    }
    public void setRole(String role)
    {
        this.role=role;
    }
    public String getRole()
    {        return this.role;
    }
    public void setUsername(String username)
    {
        this.username=username;
    }
    public String getUsername()
    {        return this.username;
    }
    public void get()
    {
        _UserAccountModel result = (_UserAccountModel) super.getModel();
        if(result!=null)
        {
            setNip(result.getNip());
            setName(result.getName());
            setPassword(result.getPassword());
            setEmail(result.getEmail());
            setRole(result.getRole());
            setUsername(result.getUsername());
        }
    }
}
