/** 
 * Autogenerated by Recite18th at Sat Jul 09 13:10:47 WIT 2011
 * 
 */

package application.models;
import recite18th.model.Model;
import application.models._AksesModel;
public class AksesModel extends _AksesModel
{
    public AksesModel()
    {
        super();
    }
}
