/** 
 * Autogenerated by Recite18th at Sat Jul 09 14:18:25 WIT 2011
 * 
 */

package application.models;
import recite18th.model.Model;
import application.models._BagianUnitKerjaModel;
public class BagianUnitKerjaModel extends _BagianUnitKerjaModel
{
    public BagianUnitKerjaModel()
    {
        super();
    }
}
