/** 
 * Autogenerated by Recite18th at Sat Jul 09 13:10:47 WIT 2011
 * 
 */

package application.models;
import recite18th.library.Db;
import recite18th.model.Model;
public class CutiModel extends _CutiModel
{
    public CutiModel()
    {
        super();
    }
    public String nama_pegawai;
    public void setNama_pegawai(String nama_pegawai)
    {
        this.nama_pegawai = nama_pegawai;
    }
    
    public String getNama_pegawai()
    {
        return Db.findValue("pegawai","nama_pegawai", "nip='" + nip + "'");
    }
    
      
    @Override
    public void overrideDefaultValue(Model model) {
        PegawaiModel pegawaiTerpilih = (PegawaiModel) session.getAttribute("pegawai_terpilih");
        CutiModel cutiModel = (CutiModel) model;
        cutiModel.setNip(pegawaiTerpilih.getNip());
    }
}
