/** 
 * Autogenerated by Recite18th at Sat Jul 09 13:10:48 WIT 2011
 * 
 */

package application.models;
import recite18th.model.Model;
import application.models._PegawaiModel;
public class PegawaiModel extends _PegawaiModel
{
    public PegawaiModel()
    {
        super();
    }
}
