/** 
 * Autogenerated by Recite18th at Sat Jul 09 13:10:48 WIT 2011
 * 
 */

package application.models;
import recite18th.model.Model;
import application.models._SubUnitKerjaModel;
public class SubUnitKerjaModel extends _SubUnitKerjaModel
{
    public SubUnitKerjaModel()
    {
        super();
    }
}
