/** 
 * Autogenerated by Recite18th at Sat Jul 09 13:10:49 WIT 2011
 * 
 */

package application.models;
import recite18th.model.Model;
import application.models._UnitKerjaModel;
public class UnitKerjaModel extends _UnitKerjaModel
{
    public UnitKerjaModel()
    {
        super();
    }
}
